### ISSUE TITLE
Update navbar UI

### ISSUE THREAD

**Issue by QuocZuong** [QuocZuong/threads#1]
Update navbar UI

from:
![image](https://github.com/QuocZuong/threads/assets/110612155/7bae5b85-d733-4735-99f9-b7a743920fc8)
to:
![image](https://github.com/QuocZuong/threads/assets/110612155/def92075-d226-4ced-b913-da693ea5628a) (go to Thread for more detail)

**Comment by PhenChua29** [comment]
Just update the outlook, does not need to have to be functional.

**ext: 1h**
