### ISSUE TITLE
Fix UI dark mode copy link button

### ISSUE THREAD

**Issue by QuocZuong** [QuocZuong/threads#15]
Copy link button show wrong color in white mode

<img width="869" alt="image" src="https://github.com/QuocZuong/threads/assets/110612155/f39054e0-55e0-4342-bb68-639d12d97f96">

**Comment by QuocZuong** [comment]
est: 2h

**Comment by BaoGfpt** [comment]
![image](https://github.com/QuocZuong/threads/assets/135344404/93b4655e-a503-4d59-b88a-491db4df288c)

component has been delete from issue #5, so i can't fix problem has'nt exist. pls check aga

**Comment by QuocZuong** [comment]
ok, we don't need to do this anymore
