### ISSUE TITLE
Fix hover effect in light mode in post detail page

### ISSUE THREAD

**Issue by QuocZuong** [QuocZuong/threads#16]
when hover post detail function it show wrong color
![Uploading image.png…]()

**Comment by QuocZuong** [comment]
![Uploading image.png…]()

est: 6 hours

**Comment by QuocZuong** [comment]
![image](https://github.com/QuocZuong/threads/assets/110612155/71ed77ca-6aa6-4889-8fad-3dd9f9b74ce3)

**Comment by BaoGfpt** [comment]
![image](https://github.com/QuocZuong/threads/assets/135344404/62b62f51-7cb0-47e8-82e6-822d84892b4e)

can't find out problem to fix, pls check aga

**Comment by QuocZuong** [comment]
Go to home page or post detail then click on toggle theme icon then hover again to see bug
<img width="76" alt="image" src="https://github.com/QuocZuong/threads/assets/110612155/e201b535-ab72-40b0-bb00-f8ea25edc6e1">
